version: "3.8"
services:
  mongo:
    image: mongo:6.0
    restart: always
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"

  app:
    build: .
    depends_on:
      - mongo
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - MONGO_URI=mongodb://mongo:27017/school_db
      - JWT_SECRET=supersecretjwt
      - ADMIN_EMAIL=admin@school.com
      - ADMIN_PASSWORD=admin123

volumes:
  mongo_data:
